### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-collect-and-display-information-kPt9Fl#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://KatieMFritz.github.io/MI-000-SS00-000-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] The generated profile's preview should render as HTML (i.e. you don't see the raw code, just the result)
- [x] The generated HTML inside the `<pre><code></code></pre>` elements should display the raw HTML code that's used in the preview
- [x] All JavaScript is in a separate `.js` file

**Comment by chrisvfritz** [comment]
Looks great! :shipit:
